apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
    - name: app-resource
      image: gcr.io/kuar-demo/kuard-amd64:1
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
