
apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demo
spec:
  containers:
  - name: app-livenessprob
    image: gcr.io/k8s-k3s/demo:v1.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10

