
apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  - name: debian-container
    image: debian:latest
    command: ["/bin/sh", "-c"]
    args:
    - while true; do date > index.html; sleep 1; done
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    emptyDir: {}

