
apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    name: app-resource
    readinessProbe:
      httpGet:
        path: /
        port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
  ports:
  - containerPort: 8080

