
apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule:
    - cron: 0,5,10,15,20,25,30,35,40,45,50,55 * * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: bash
            command: ["echo", "Hello world"]
          restartPolicy: OnFailure

