apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
    - name: app
      image: gcr.io/kuar-demo/kuard-amd64:1
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
      volumeMounts:
        - name: appdata
          mountPath: /data
  volumes:
    - name: appdata
      hostPath:
        path: /var/lib/app
  restartPolicy: Always
